export const definedSkills = [
    { text: 'Organic Chemistry' },
    { text: 'Analytical Chemistry' },
    { text: 'Physical Chemistry' },
    { text: 'Inorganic Chemistry' },
    { text: 'Biochemistry' },
    { text: 'Material Chemistry' },
    { text: 'Theoretical Chemistry' },
    { text: 'Biophysics' },
    { text: 'Catalysis' },
    { text: 'Chemical Biology' },
    { text: 'Energy' },
    { text: 'Organimetallics' },
    { text: 'Environmental Chemistry' },
    { text: 'Materials and Nanoscience' },
    { text: 'Polymer Chemistry' },
    { text: 'Research' },
    { text: 'Workshops' },
    { text: 'Corporate Strategy' },
    { text: 'Management Consulting' },
    { text: 'Program Management' },
    { text: 'Science communication' },
    { text: 'Scientific Writing' },
    { text: 'Technology Roadmapping(TR)' },
    { text: 'Open Innovation' },
    { text: 'Innovation Management' },
    { text: 'Technology Scouting' },
    { text: 'Materials Science' },
    { text: 'Chemistry' },
    { text: 'Polymers' },
    { text: 'R&D' },
    { text: 'Social Media' },
    { text: 'Materials' },
    { text: 'Product Development' },
    { text: 'Research and Development(R&D)' },
    { text: 'Nanotechnology' },
    { text: 'Science' },
    { text: 'Nanomaterials' },
    { text: 'Web Development' },
    { text: 'Product Innovation' },
    { text: 'Business Strategy' },
    { text: 'Strategy' },
    { text: 'Photography' },
    { text: 'Change Management' },
    { text: 'Product Management' },
    { text: 'Strategic Planning' },
    { text: 'Technology Transfer' },
    { text: 'Ruby on Rails' },
    { text: 'SharePoint' },
    { text: 'Management' },
    { text: 'Polymer Chemistry' },
    { text: 'Crowdsourcing' },
    { text: 'Biomimicry' },
    { text: 'Idea Incubation' },
    { text: 'Web Application Development' },
    { text: 'Scouting' },
    { text: 'Collaborative Innovation' },
    { text: 'Innovation' },
    { text: 'Knowledge' },
    { text: 'HYPE Ideation' },
    { text: 'Statistical Data Analysis' },
    { text: 'Project Management' },
    { text: 'IT Strategy' },
    { text: 'Machine Learning' },
    { text: 'Grant Writing' },
    { text: 'Linguistics' },
    { text: 'Quantitative Research' },
    { text: 'Market Research' },
    { text: 'Git' },
    { text: 'Public Speaking' },
    { text: 'Culture Change' },
    { text: 'Technical Consultation' },
    { text: 'Service Development' },
    { text: 'IT Procurement' },
    { text: 'Multivariate Statistics' },
    { text: 'Project Communications' },
    { text: 'Qualitative & Quantitative Research Methodologies' },
    { text: 'Grant Preparation' },
    { text: 'Corpus Linguistics' },
    { text: 'User Research' },
    { text: 'Customer Satisfaction Research' },
    { text: 'English' },
    { text: 'Grant Administration' },
    { text: 'Digital Strategy' },
]
