version: '3'

services:
  nginx: 
      build:
        args:
          TEMPLATE: staging.conf.template
          
  cms:
    container_name: cms
    image: strapi/strapi
    volumes:
      - type: bind
        source: ./cms
        target: /srv/app
    depends_on:
      - postgres

  nest-backend:
    container_name: nest-backend
    image: nest-backend:dev
    build:
      context: ./nest-backend
      args:
        NODE_ENV: development
    volumes:
      - type: bind
        source: ./nest-backend
        target: /app
      - /app/node_modules
    depends_on: 
      - postgres

  nlp:
    build: ./TextSummarizer
    image: nlp:dev

  web-app:
    container_name: web-app
    image: web-app:dev
    build:
      context: ./web-app-material
      args:
        NODE_ENV: development
    ports:
      - 3001:3000
    volumes:
      - type: bind
        source: ./web-app-material
        target: /app
      - /app/node_modules
    depends_on: 
      - nest-backend
      - cms

